[package]
  name = "typenum"
  build = "src/__private/build.rs"
  version = "1.2.0"
  authors = [
    "Paho Lurie-Gregg <paho@paholg.com>",
    "Andre Bogus <bogusandre@gmail.com>"
  ]
  description = "Typenum is a Rust library for type-level numbers evaluated at compile time. It currently supports bits, unsigned integers, and signed integers."
  homepage = "http://paholg.com/project/typenum"
  documentation = "http://paholg.com/typenum"
  repository = "https://github.com/paholg/typenum"
  readme = "README.md"
  license = "MIT/Apache-2.0"

[lib]
  name = "typenum"

[features]
  no_std = []
